### ISSUE TITLE
Unable to push Camtasia via autopkg

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/bkerns-recipes#24] opened 2020-04-29 18:56 UTC
TechSmithCamtasia.jss.recipe
        Error in com.github.autopkg.kernsb.jss.TechSmithCamtasia: Processor: CodeSignatureVerifier: Error: Error processing path '/private/tmp/dmg.Rnyoem/Camtasia 2019.app

**Comment by WaveBirdDash** [comment] 2020-04-29 21:37
This is a duplicate of #23.

**Comment by kernsb** [comment] 2020-04-30 13:39
Fixed by 74f08b9 merge

**Closed as completed by kernsb** 2020-04-30 13:39 UTC
